fruits = ["apple", "banana", "orange", "mango"]
print(type(fruits))
print(fruits)
print(fruits[0])
print(fruits[3])
print(fruits[2])
fruits.append("papaya")
print(fruits)
print(len(fruits))
print("papaya" in fruits)
print("guava" in fruits)
print(fruits.pop())
print(fruits)
print(fruits.pop())
print(fruits)
print(fruits.pop())
print(fruits)